default:
    image: python:3.8
    before_script:
       - apt-get update
       - apt-get install -y python3-pip
       - pip install -r requirements.txt
stages:
    - test

test:
    script:
        - coverage run -m xmlrunner --output-file report.xml
        - coverage report --omit=tests/* --precision=2
        - coverage xml
    artifacts:
        when: always
        paths:
            - coverage.xml
            - report.xml
        reports:
            cobertura: coverage.xml
            junit: report.xml
      


  
