image: python:3.7-alpine

pages:
  stage: build
  script:
  - pip install -U sphinx
  - sphinx-build -b html docs/source public
  artifacts:
    paths:
    - public
  only:
  - master

deploy:
  stage: deploy
  variables:
    "EOS_PATH": "/eos/user/i/idinu"
  image: gitlab-registry.cern.ch/ci-tools/ci-web-deployer
  script:
    - deploy-eos

